[settings]
experimental = true
lockfile = true

[tools]
"aqua:anthropics/claude-code" = "latest"
"aqua:cli/cli" = "latest"
"npm:skills" = "latest"
"vfox:mise-plugins/vfox-1password" = "latest"

elixir = "latest"
erlang = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
kubectl = "latest"
nodejs = "latest"
podman = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
terraform = "latest"
zellij = "latest"

[env]
NUM_CPUS = "{{ (num_cpus() | int / 2) | int }}"
MIX_OS_DEPS_COMPILE_PARTITION_COUNT = "{{ (num_cpus() | int / 2) | int }}"
