return {

  { "L3MON4D3/LuaSnip", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "ahmedkhalf/project.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  -- { "echasnovski/mini.comment",                    enabled = false },
  { "echasnovski/mini.files", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  -- { "echasnovski/mini.surround",                   enabled = false },
  { "folke/edgy.nvim", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "gbprod/yanky.nvim", enabled = false },
  { "gbprod/yanky.nvim", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  -- { "hrsh7th/cmp-buffer",                          enabled = false },
  -- { "hrsh7th/cmp-nvim-lsp",                        enabled = false },
  -- { "hrsh7th/nvim-cmp",                            enabled = false },
  -- { "hrsh7th/cmp-path",                            enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "nvim-neotest/neotest", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  -- { "nvim-telescope/telescope.nvim",               enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  -- { "saadparwaiz1/cmp_luasnip",                    enabled = false },
  { "zbirenbaum/copilot-cmp", enabled = false },
  { "zbirenbaum/copilot.lua", enabled = false },
>>>>>>> Stashed changes

  "janko-m/vim-test",
  "jremmen/vim-ripgrep",
  "nvim-lua/plenary.nvim",
  "nvim-treesitter/nvim-treesitter-textobjects",
  "godlygeek/tabular",
  "tpope/vim-projectionist",
  "iamcco/markdown-preview.nvim",
  "tpope/vim-unimpaired",
  "tpope/vim-fugitive",
  "tpope/vim-surround",
}
