#! /bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Linux" ]; then
  if command -v pacman >/dev/null 2>&1; then
    # install base dev packages for developing on manjaro linux
    echo "sudo pacman -S neovim tmux yarn postresql jq"
    sudo pacman -S neovim tmux yarn postgresql jq xclip
  fi
fi

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi

# install asdf
if [ ! -d ~/.asdf ]; then
  echo "git clone https://github.com/asdf-vm/asdf.git ~/.asdf"
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
fi

echo "cd ~/.asdf"
cd ~/.asdf

echo "git checkout \"$(git describe --abbrev=0 --tags)\""
git checkout "$(git describe --abbrev=0 --tags)"

# install all the languages in ~/.tool-versions
echo "asdf plugin-add elixir" 
asdf plugin-add elixir

echo "asdf plugin-add erlang" 
asdf plugin-add erlang

echo "asdf plugin-add node" 
asdf plugin-add node

echo "asdf plugin-add rust" 
asdf plugin-add rust

echo "asdf install" 
asdf install

# install ember
echo "yarn global add ember-cli" 
yarn global add ember-cli

#install phx.new for elixir
echo "mix archive.install hex phx_new" 
mix archive.install hex phx_new
